name: Deploy Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # Actualizado a v4
        with:
          version: 9.15.1 # La version exacta de tu package.json

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build Project
        run: |
          # Usamos --no-frozen-lockfile para evitar el error que mencionaste
          pnpm install --no-frozen-lockfile 
          pnpm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Incluimos drizzle.config.ts y la carpeta de migraciones
          source: "dist,package.json,pnpm-lock.yaml,drizzle.config.ts,src/infrastructure/db/migrations" 
          target: "~/apps/backend"

      - name: Migrate and Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/apps/backend
            pnpm install --prod --no-frozen-lockfile
            
            # EJECUTAR MIGRACIONES
            echo "Ejecutando migraciones de Drizzle..."
            pnpm run db:migrate
            
            # REINICIAR APP
            pm2 restart backend-api || PORT=3000 pm2 start dist/infrastructure/server.js --name "backend-api"
            pm2 save