name: Deploy Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Build Project
        run: |
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 120s # Aumentamos tiempo de conexión
          command_timeout: 10m # Tiempo de sobra para el copiado
          # EXTREMADAMENTE IMPORTANTE: Asegúrate de que estas carpetas existan en tu repo
          source: "dist,package.json,pnpm-lock.yaml,drizzle.config.ts,drizzle"
          target: "/root/apps/backend"
          strip_components: 0
          overwrite: true

      - name: Migrate and Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /root/apps/backend
            
            # Instalar dependencias de producción
            pnpm install --prod --no-frozen-lockfile
            
            # Ejecutar migraciones de Drizzle
            echo "Ejecutando migraciones..."
            pnpm run db:migrate
            
            # Reiniciar con PM2 (Ruta absoluta del main)
            pm2 restart backend-api || PORT=3000 pm2 start dist/infrastructure/server.js --name "backend-api"
            pm2 save